apiVersion: v1
kind: Service
metadata:
  name: gitlab-app-service
  namespace: prod
spec:
  type: NodePort
  selector:
    app: gitlab-app
  ports:
    - protocol: TCP
      port: {{ .Values.appPort }}
      targetPort: 80     
      nodePort: 30002
